name: Review

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true
    # inputs:
    #   ABC:
    #     required: true

permissions:
  contents: read

jobs:
  # Tes
  tes:
    name: Tes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # # Checkout
      - name: Checkout
        uses: mnrendra/first-action@093cb703244d419404432749259a9817b2e4c17a
        with:
          token: ${{ secrets.TOKEN }}
      # Do Tes
      - name: Do Tes
        uses: ./.github/actions/tes
        with:
          base-remote: --status
          token: ${{ secrets.TOKEN }}
